services:
  - type: web
    name: result-system
    runtime: php
    buildCommand: composer install
    startCommand: php -S 0.0.0.0:$PORT router.php
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_PORT
        sync: false
